name: "Integration tests"
description: "Run tests with BTP services being bound"
inputs:
  CF_API:
    description: "Cloud Foundry API endpoint"
    required: true
  CF_USERNAME:
    description: "Cloud Foundry username"
    required: true
  CF_PASSWORD:
    description: "Cloud Foundry password"
    required: true
  CF_ORG:
    description: "Cloud Foundry organization"
    required: true
  CF_SPACE:
    description: "Cloud Foundry space"
    required: true
  NODE_VERSION:
    description: "Node.js version to use for tests"
    required: true
runs:
  using: "composite"
  steps:
    - name: Install dependencies and Cloud Foundry CLI (v8.9.0)
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y libc6 wget tar
        wget "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=8.9.0&source=github-rel" -O cf-cli.tar.gz
        tar -xvzf cf-cli.tar.gz
        sudo mv cf /usr/local/bin/
        sudo mv cf8 /usr/local/bin/
        cf --version

    # BTP Auth
    # Uncomment when you want to run hybrid integration tests
    - name: Authenticate with Cloud Foundry
      shell: bash
      run: |
        echo "::debug::CF_API=${{ inputs.CF_API }}"
        for i in {1..3}; do
          cf login -a ${{ inputs.CF_API }} -u ${{ inputs.CF_USERNAME }} -p ${{ inputs.CF_PASSWORD }} -o ${{ inputs.CF_ORG }} -s ${{ inputs.CF_SPACE }} && break
          echo "cf login failed, retrying ($i/3)..."
          sleep 10
          if [ "$i" -eq 3 ]; then
            echo "❌ cf login failed after 3 attempts."
            exit 1
          fi
        done

    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Set CDS version-specific dependencies
      shell: bash
      run: |
        if [ "${{ matrix.cds-version }}" == "8" ]; then
          echo "Installing CDS 8 compatible packages..."
          npm pkg set "devDependencies.@cap-js/sqlite=^1.0.0"
          npm pkg set "overrides.@cap-js/sqlite=^1.0.0"
          npm pkg set "overrides.@cap-js/hana=^1.0.0"
          npm pkg set "overrides.@cap-js/db-service=^1.0.0"
          cd test/incidents-app
          npm pkg set "dependencies.@cap-js/hana=^1.0.0"
          npm pkg set "dependencies.@cap-js/db-service=^1.0.0"
          cd ../..
        fi

    - name: Install global CDS
      shell: bash
      run: npm i -g @sap/cds-dk@${{ matrix.cds-version }}
      shell: bash
    - name: Install root dependencies
      shell: bash
      run: |
        npm install @sap/cds@${{ matrix.cds-version }}
        npm install

    # HANA Cloud Deployment and binding
    # Uncomment when you want to run your hybrid integration tests against HANA Cloud
    # Replace print with your actual project name
    - name: Set node env for HANA
      run: echo "NODE_VERSION_HANA=$(echo ${{ inputs.NODE_VERSION }} | tr . _)" >> $GITHUB_ENV
      shell: bash
    Deploy model to HANA
    - name: Create HDI Container
      shell: bash
      run: cf create-service hana hdi-shared cap-js-print-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}-$NODE_VERSION_HANA-${{ matrix.cds-version }}
    - run: cd tests/incidents-app/ && cds deploy --to hana:cap-js-print-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}-$NODE_VERSION_HANA-${{ matrix.cds-version }}
      shell: bash
    # Bind HANA Cloud instance
    - run: cds bind db -2 cap-js-print-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}-$NODE_VERSION_HANA-${{ matrix.cds-version }} -o package.json
      shell: bash

    # Bind against BTP services
    # Uncomment when actual BTP services should be used
    - run: cds bind print-service -2 print-service -o package.json
      shell: bash
    # Run tests in hybrid mode
    - run: npm run test:hybrid
      shell: bash

    # HANA Cleanup
    # Uncomment when you want to run your hybrid integration tests against HANA Cloud
    # Replace print with your actual project name
    - name: Delete HDI Container Key
      if: ${{ always() }}
      run: cf delete-service-key cap-js-print-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}-$NODE_VERSION_HANA-${{ matrix.cds-version }} cap-js-print-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}-$NODE_VERSION_HANA-${{ matrix.cds-version }}-key -f
      shell: bash
    # Somehow first delete always fails with a "ongoing operation on service binding" error
    - name: Delete HDI Container
      if: ${{ always() }}
      shell: bash
      run: |
        for i in {1..3}; do
          cf delete-service cap-js-print-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}-$NODE_VERSION_HANA-${{ matrix.cds-version }} -f && break
          echo "HDI container delete failed, retrying ($i/3)..."
          sleep 10
          if [ "$i" -eq 3 ]; then
            echo "❌ HDI container delete failed after 3 attempts."
            exit 1
          fi
        done
